# Generated by Django 6.0.4 on 2026-05-15 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_deviceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='ambulance_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo/Simulation'), ('speed_drop', 'Speed Drop'), ('impact', 'Impact/Jerk'), ('manual', 'Manual SOS'), ('zone', 'Safety Zone'), ('vision', 'Vision Observation')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('call', 'Phone Call'), ('push', 'Push Notification'), ('email', 'Email'), ('ambulance', 'Ambulance Dispatch')], max_length=20),
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('suspicion', 'Suspicion'), ('guardian_notified', 'Guardian Notified'), ('rider_safe', 'Rider Marked Safe'), ('rider_confirmed', 'Rider Confirmed Accident'), ('ambulance_requested', 'Ambulance Requested')], max_length=30)),
                ('status', models.CharField(default='created', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_events', to='alerts.emergencyalert')),
            ],
        ),
    ]
